# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Build at 00:00 on every 13th day-of-month.
  schedule:
    - cron: "0 0 */13 * *"
  # Triggers the workflow on push or pull request events but only for the test5 branch
  push:
    branches: [ test5 ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ test5 ]
    paths-ignore: [ '**/README.md' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-devel-exp-wow64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Prerequisites
        run: |
          wget -q "https://github.com/AppImageCrafters/appimage-builder/releases/download/Continuous/appimage-builder-1.1.1.dev32+g2709a3b-x86_64.AppImage" -O appimage-builder ; chmod +x appimage-builder ; ./appimage-builder --appimage-extract &>/dev/null
          mkdir -p /usr/share/icons/hicolor/scalable/ ; cp wine.svg /usr/share/icons/hicolor/scalable/
          # wget -q "https://github.com/probonopd/static-tools/releases/download/continuous/mksquashfs-x86_64" -O squashfs-root/usr/bin/mksquashfs
          cp runtime/mksquashfs squashfs-root/usr/bin/mksquashfs
          rm appimage-builder ; sed -i 's|xz|zstd|' squashfs-root/usr/lib/python3.8/site-packages/appimagebuilder/modules/prime/appimage_primer.py
          # stable
          echo "WINE_VER=devel-wow64_$(wget -qO- https://github.com/mmtrt/Wine-Builds/releases/expanded_assets/wow64 | grep -Eo '/wine-[0-9].*xz"' | cut -d'-' -f2 | head -1)" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Build appimage
        run: |
          # add dir dist
          mkdir dist

          squashfs-root/AppRun --recipe wine-devel-exp-wow64.yml
          mv *AppImage* dist/.

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: wine-devel-exp-wow64-continuous-x86_64.AppImage
          path: 'dist'

  build-staging-exp-wow64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Prerequisites
        run: |
          wget -q "https://github.com/AppImageCrafters/appimage-builder/releases/download/Continuous/appimage-builder-1.1.1.dev32+g2709a3b-x86_64.AppImage" -O appimage-builder ; chmod +x appimage-builder ; ./appimage-builder --appimage-extract &>/dev/null
          mkdir -p /usr/share/icons/hicolor/scalable/ ; cp wine.svg /usr/share/icons/hicolor/scalable/
          # wget -q "https://github.com/probonopd/static-tools/releases/download/continuous/mksquashfs-x86_64" -O squashfs-root/usr/bin/mksquashfs
          cp runtime/mksquashfs squashfs-root/usr/bin/mksquashfs
          rm appimage-builder ; sed -i 's|xz|zstd|' squashfs-root/usr/lib/python3.8/site-packages/appimagebuilder/modules/prime/appimage_primer.py
          # stable
          echo "WINE_VER=staging-wow64_$(wget -qO- https://github.com/mmtrt/Wine-Builds/releases/expanded_assets/wow64 | grep -Eo '/wine-[0-9].*xz"' | cut -d'-' -f2 | head -1)" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Build appimage
        run: |
          # add dir dist
          mkdir dist

          squashfs-root/AppRun --recipe wine-staging-exp-wow64.yml
          mv *AppImage* dist/.

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: wine-staging-exp-wow64-continuous-x86_64.AppImage
          path: 'dist'


  release-devel-exp-wow64:
      needs: [build-devel-exp-wow64]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: wine-devel-exp-wow64-continuous-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: wine-devel-wow64 (experimental)
            automatic_release_tag: test5-devel
            prerelease: false
            draft: false
            files: |
              wine-devel-exp-wow64-continuous-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}

  release-staging-exp-wow64:
      needs: [build-staging-exp-wow64]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: wine-staging-exp-wow64-continuous-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: wine-staging-wow64 (experimental)
            automatic_release_tag: test5-staging
            prerelease: false
            draft: false
            files: |
              wine-staging-exp-wow64-continuous-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
